---aaa
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhoujie.
--- DateTime: 2022/9/30 17:00
---@class lib996
lib996 = {}

--加载文件
---@param filename string文件路径
---@return 加载文件
function lib996:include(filename) end

function lib996:release_print(msg) end

--修改人物当前血量
---@param actor 对象
---@param operate string操作符 + - =
---@param nvalue string血量
---@param effid bool素材ID
function lib996:humanhp(actor, operate, nvalue, effid) end
--修改人物当前蓝量
---@param actor 对象
---@param operate string操作符 + - =
---@param nvalue string血量
---@param effid bool素材ID
function lib996:humanmp(actor, operate, nvalue, effid) end


---获取人物/怪物 相关信息
---@param actor 对象
---@param id integer
---@param param param
function lib996:getbaseinfo(actor, id, param)  end

--发送聊天框消息
---@param actor object玩家对象
---@param type int1自己2全服3行会4当前地图5组队
---@param msg str消息内容
function lib996:sendmsg(actor, type,  msg) end

---在人物身上播放特效
---@param actor object玩家对象
---@param effectid int特效ID
---@param offsetX int相对于人物偏移的X坐标
---@param offsetY int相对于人物偏移的Y坐标
---@param times int播放次数0一直播放
---@param behind int播放模式0前面1后面
---@param selfshow int仅自己可见0否1是
function lib996:playeffect(actor,effectid,offsetX,offsetY,times,behind,selfshow) end

---检测人物称号
---@param actor object玩家对象
---@param title string称号
---@return boolean
function lib996:checktitle(actor,title) end


---添加称号
---@param actor object玩家对象
---@param name string称号物品名称
---@return boolean
function lib996:confertitle(actor,name) end

---清除人物身上播放的特效
---@param actor object玩家对象
---@param effectid int特效ID
function lib996:clearplayeffect(actor,effectid) end

---删除称号
---@param actor object玩家对象
---@param name string称号物品名称
function lib996:deprivetitle(actor,name) end


---changemoney
---@param actor object玩家对象
---@param id int货币ID（1-100）
---@param opt string操作符 + - =
---@param count int数量
---@param msg string备注内容
---@param send 	bool是否立即刷新
---@return boolean
function lib996:changemoney(actor,id,opt,count,msg,send) end

---通知客户端显示显示表单
---@param actor object玩家对象
---@param file string文件名
---@param parent stringWin_Create节点ID
function lib996:showformwithcontent(actor, file, parent) end

---自定义变量排序
---@param varname strng排序变量名
---@param itype int0所有玩家1在线玩家2行会
---@param sort int0升序1降序
---@param count int数据量前几名0或空取所有
---@return table
function lib996:sorthumvar(varname,itype,sort,count) end

---获取对象int型变量
---@param Type int类型0玩家1行会2地图
---@param actor object玩家对象
---@param sVarName string变量名
---@return int或者nil
function lib996:getint(Type,actor,sVarName) end

---获取系统str型变量
---@param sVarName string变量名
---@return string或者nil
function lib996:getsysstr(sVarName) end

---获取系统int型变量
---@param sVarName string变量名
---@return int或者nil
function lib996:getsysint(sVarName) end

---添加技能
---@param actor object玩家对象
---@param skillid int技能ID
---@param level int技能等级
function lib996:addskill(actor,skillid,level) end

---字符串转换成表格
---@param str string要转换的字符串
---@return table
function lib996:json2tbl(str) end

---表格转换成字符串
---@param tab table要转换的表格
---@return string
function lib996:tbl2json(tab) end

-----humvarrank
--function lib996:humvarrank() end


---设置对象int型变量
---@param Type int类型0玩家1行会2:地图
---@param actor obj对象
---@param sVarName string变量名
---@param nValue int变量值
function lib996:setint(Type,actor,sVarName,nValue) end

---设置对象str型变量
---@param Type int类型0玩家1行会2地图
---@param actor obj对象
---@param sVarName string变量名
---@param nValue str变量值
function lib996:setstr(Type,actor,sVarName,nValue) end

---设置系统int型变量
---@param sVarName string变量名
---@param nValue int变量值
function lib996:setsysint(sVarName,nValue) end


---设置系统string型变量
---@param sVarName string变量名
---@param nValue string变量值
function lib996:setsysstr(sVarName,nValue) end

---获取用户变量位次
---@param actor parent用户
---@param varname 变量名
---@param type 0=所有玩家 1=在线玩家 2=行会变量
---@param sort 0升序1降序
---@return number位次
function humvarrank(actor, varname, type, sort) end

---根据玩家名获取玩家对象
---@param name string玩家名字
---@return object玩家对象
function lib996:getplayerbyname(name) end

---查询人物货币
---@param actor object玩家对象
---@param id int货币ID（1-100）
---@return int对应的货币数量
function lib996:querymoney(actor,id) end


---设置玩家转生等级
---@param acto object玩家对象
---@param n int前转生等级
function lib996:setrelevel(acto,n) end


---获取玩家转生等级
---@param actor object	玩家对象
---@return int
function lib996:getrelevel(actor) end

---获取人物临时属性
---@param actor object玩家对象
---@param nWhere int对应cfg_att_score属性ID
---@return int对应属性值
function lib996:gethumnewvalue(actor,nWhere) end

---修改人物临时属性
---@param actor object玩家对象
---@param nWhere int对应cfg_att_score属性ID
---@param nValue int对应属性值
---@param nTime int有效时间，秒
function lib996:changehumnewvalue(actor,nWhere,nValue,nTime) end

---根据装备位获取装备对象
---@param actor object玩家对象
---@param where int装备位置
---@return object成功：返回装备对象失败：返回"0"
function lib996:linkbodyitem(actor,where) end

---获取物品实体信息
---@param actor 玩家对象
---@param item object物品对象
---@param id int1唯一ID2物品ID3剩余持久4最大持久5叠加数量6绑定状态
---@return int对应数值不存在为0
function lib996:getiteminfo(actor,item,id) end

---根据物品唯一ID获得物品对象
---@param actor object玩家对象
---@param makeindex int物品唯一ID
---@return object返回对应的物品对象如果检索不到返回nil
function lib996:getitembymakeindex(actor,makeindex) end

---根据道具自定义属性组获取该组属性
---@param actor object玩家对象
---@param makeid int道具唯一id
---@param nTag int属性组-1
---@return str根据道具自定义属性组获取该组属性
function lib996:getitemattr(actor, makeid, nTag) end

---删除道具自定义属性
---@param actor object玩家对象
---@param makeid int道具唯一id
---@param type int属性组
---@param attid int属性id为0时清除该组所有属性
---@return true成功false失败
function lib996:delitemattr(actor,makeid,type,attid) end

---跳转到地图随机坐标
---@param actor object玩家对象
---@param mapname string地图名
function lib996:map(actor,mapname) end

---采集挖矿等进度条操作
---@param actor object玩家对象
---@param time int进度条时间秒
---@param succ string成功后跳转的函数
---@param msg string提示消息
---@param canstop 中断0 1
---@param fail string中断触发的函数
function lib996:showprogressbardlg(actor,time,succ,msg,canstop,fail) end


---根据怪物id返回怪物基础信息
---@param idx object怪物的IDX
---@param id int1怪物名称2怪物名字颜色3杀死怪物获得的经验值
function lib996:getmonbaseinfo(idx,id) end

---获取玩家转生等级
---@param actor object玩家对象
---@return int玩家转生等级
function lib996:getrelevel(actor) end

---设置玩家转生等级
---@param acto object玩家对象
---@param n int转生等级
function lib996:setrelevel(acto,n) end

---获取玩家当前等级
---@param actor object玩家对象
---@return int玩家当前等级
function lib996:getlevel(actor) end

---设置玩家当前等级
---@param actor object玩家对象
---@param n int等级
function lib996:setlevel(actor, n) end

---任务被点击时
---@param actor object玩家对象
---@param id int任务id
function clicknewtask(actor,id) end

---新建任务时触发
---@param actor object玩家对象
---@param id int新建的任务id
function picktask(actor, id) end

---任务变化时
---@param actor object玩家对象
function changetask(actor) end

---删除计划任务
---@param id int任务计划id
function lib996:delscheduled(id) end

---判断计划任务是否存在
---@param id int任务计划id
---@return bool
function lib996:hasscheduled(id) end

---添加计划任务
---@param id int任务计划id不可重复
---@param name str任务计划名称
---@param itype int0指定时间1每天执行2每周执行3每月执行
---@param strtime str时间表详细见示例多时间#拼接
---@param strfun str回调函数
---@param param str999#adas#1a1a
---@return bool
function lib996:addscheduled(id,name,itype,strtime,strfun,param) end

---任务置顶显示
---@param actor object玩家对象
---@param id int任务id
function lib996:tasktopshow(actor,id) end

---删除任务
---@param actor object玩家对象
---@param id int任务id
function lib996:newdeletetask(actor,id) end

---完成任务
---@param actor object玩家对象
---@param id int任务id
function lib996:newcompletetask(actor,id) end

---刷新进行中任务状态
---@param actor object玩家对象
---@param id int任务id
---@param a str参数1
---@param b str参数2
---@param c str参数3
---@param d str参数4
---@param e str参数5
---@param f str参数6
---@param g str参数7
---@param h str参数8
---@param i str参数9
---@param j str参数10
function lib996:newchangetask(actor,id,a,b,c,d,e,f,g,h,i,j) end

---新建任务
---@param actor object玩家对象
---@param id int任务id
---@param a str参数1
---@param b str参数2
---@param c str参数3
---@param d str参数4
---@param e str参数5
---@param f str参数6
---@param g str参数7
---@param h str参数8
---@param i str参数9
---@param j str参数10
function lib996:newpicktask(actor,id,a,b,c,d,e,f,g,h,i,j) end

---添加镜像地图
---@param oldMap string原地图ID
---@param NewMap string新地图ID此id可作为临时对象使用
---@param NewName string新地图名
---@param time int有效时间秒
---@param BackMap string回城地图有效时间结束后传回去的地图
function lib996:addmirrormap(oldMap,NewMap,NewName,time,BackMap) end

---获取对象名称
---@param actor object对象
---@return str返回对象名称
function lib996:getname(actor) end

---在指定地图xy坐标刷新怪物
---@param mapid object地图id
---@param x intx坐标
---@param y inty坐标
---@param monname str怪物名称
---@param range int范围
---@param count int数量
---@param color int颜色
---@return table怪物对象列表
function lib996:genmon(mapid,x,y,monname,range,count,color) end

---获取角色属性
---@param actor object玩家对象
---@param attid int属性id
---@return int属性值
function lib996:attr(actor,attid) end

---刷新人物属性
function lib996:recalcabilitys(actor) end

---发送屏幕滚动信息
---@param actor object玩家对象
---@param flag str0发送给自己1发送所有人物2发送行会3发送当前地图4组队
---@param FColor int前景色
---@param BColor int背景色
---@param higjt int高度
---@param show int滚动次数
---@param msg str消息内容
function lib996:sendmovemsg(actor,flag,FColor,BColor,higjt,show,msg) end

---给道具增加自定义属性
---@param actor object玩家对象
---@param makeid int道具makeindex唯一id
---@param type int属性组
---@param attid int属性id
---@param attvar int属性值
function lib996:additemattr(actor,makeid,type,attid,attvar) end

---获取物品模板信息
---@param itemidORitemName intORstring物品IDOR物品名称
---@param id itemidORitemName是1名称2StdMode3Shape4重量5AniCount6最大持久7叠加数量8价格price9使用条件10使用等级11道具表常量29列12道具表常量30列
function lib996:getstditeminfo(itemidORitemName,id) end

---@return table返回所有在线玩家对象列表
function lib996:getplayerlst() end

---开/关首饰盒
---@param actor object玩家对象
---@param bState int0关闭1开启
function lib996:setsndaitembox(actor,bState) end

---添加对象定时器
---@param actor object玩家对象
---@param id int定时器id
---@param tick int执行间隔秒
---@param count int执行次数为0时不限次数
function lib996:setontimer(actor,id,tick,count) end

---添加系统定时器
---@param id int定时器id
---@param tick int执行间隔秒
---@param count int执行次数为0时不限次数
function lib996:setontimerex(id,tick,count) end

---设置人物背包格子数
---@param actor object玩家对象
---@param count int格子大小不小于46不大于126
function lib996:setbagcount( actor, count ) end

---获取人物当前佩戴称号
---@param actor object玩家对象
---@param title string称号
---@return int返回当前佩戴称号id
function lib996:getcurtitleid(actor,title) end

---获取人物所有称号
---@param actor object玩家对象
---@return table返回称号id列表
function lib996:gettitlelist(actor) end

---判断对象是否为玩家
---@param actor object	对象
---@return true是玩家false不是玩家
function lib996:isplayer(actor) end

---获取角色所有属性
---@param actor object玩家对象
---@return table所有属性值
function lib996:attrtab(actor) end

---1.NPC不在当前地图时: nRange>0: 瞬移传送到NPC附近; nRange=0: 不传送;2.NPC在当前地图时: nRange>0: 瞬移传送到NPC附近; nRange=0: 导航到NPC附近
---@param actor object玩家对象
---@param npc intnpcid
---@param rangea int范围不在此范围内则移动到npc附近
---@param rangeb int范围移动到NPC附近的范围内
function lib996:opennpcshowex(actor,npc,rangea,rangeb) end
